apiVersion: v1
kind: Service
metadata:
  name: gis
  namespace: default
  labels:
    name: gis
spec:
  ports: 
  - port: 8088
    targetPort: 8088
    protocol: TCP
    name: download
  - port: 8087
    targetPort: 8087
    protocol: TCP
    name: upload
  selector:
    k8s-app: gis
